import "x"
import a1 from "a"
import { b1, c1 } from "b"
import d1, { e1, f1 } from "c"
import * as g1 from "d"
import type a2 from "e"
import type { b2 as B2, c2 as C2 } from "f"
import type d2, { e2 as E2, f2 as F2 } from "g"
